---
title: "Fuel Estimation For Operational Performance Benchmarking"
description: |
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Welcome!

This is an exploratory project in support of the on-going Brazil-Europe Operational Performance Comparison.
The aim is to develop a data-driven approach based on the existing operational efficiency indicator methodologies.

# Overview
Air transportation has grown over the past decades.
Air traffic is projected to recover from the unprecedented decrease in demand during the COVID pandemic period, 2020-2021.

Across the globe, states have defined ambitious political goals to address the impact of climate change. 
Accordingly, there is a higher interest in monitoring/estimating the impact of operational (in)efficiency.

Operational inefficiencies typically increase the aircraft flying time (i.e. airborne and surface movement times) and , thus, engine running time.
Engine time is directly linked to fuel burn and associated emissions and pollutants.
In that respect, inefficiencies contribute to the ditremental effect of excessive emissions to climate change.

Aircraft engines produce various types of emissions. These emissions include carbon dioxide $CO_2$, water vapour ${H_2}O$, nitrogen oxides
nitrogen oxides (NOX), carbon monoxide (CO), unburned hydrocarbons (HC), sulfur oxides (SOX), particulatematter (PM), and other trace compounds. About 70 percent of aircraft emissions are CO2; followed by H2O atslightly less than 30% while the rest of the pollutant represent less than 1 percent each [source]. 
CO2 and H2O formsignificant amount of GHG emissions that can trigger climate change while NOX, CO, HC, SOX and particulate matterare always associated with air quality and subsequently public health

Operational performance benchmarking aims at understanding the similarities and differences of operational practices/concepts, technological enablers, and strategic and operational priorities in different regions.
The practice of operational performance benchmarking is well established through regular bi-regional (e.g. US/EU, BRA-EUR, CHN-EUR) or multi-regional (PWBG) comparison reports. 
These reports/groups build their joint work on harmonised practices and jointly agreed methods. 
ICAO is promoting a performance-based approach and associated benchmarking. Through its Global Air Navigation Plan (GANP), ICAO proposes a set of performance indicators to measure operational performance. 
However, to date, this set of indicators does not cater specifically for Environmental (Sustainability).
As an initial step, there is an intetest to develop tools/approaches for converting operational inefficiencies into additional fuel burn/$CO_2$ emissions. 
